### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by PikkonMG** [kodycode/CoinMarketDiscordBot#12]
[12/25/2017 09:37:20 AM](bot.py) - INFO - Starting bot..
[12/25/2017 09:37:20 AM](bot.py) - ERROR - Failed to load extension cogs.coin_market_cmd_handler

**Comment by kodycode** [comment]
Hi Pikkon,

There should be an Exception printed in the next line. If you see that there, can you post the Exception message here?

**Comment by ElDiemo** [comment]
Hi Koydcode,

is there please any setup guide on MAC? I'm not familiar with Python and step by step will be awesome.
Thank you very much

**Comment by kodycode** [comment]
Hey @ice552,

I recommend next time in the future to make a separate issue ticket in the future but in any case, there's two ways to get Python (specifically Python 3.6 in our case) on a Mac OS. You can simply use their installer from here:
https://www.python.org/downloads/mac-osx/

Or, you can install it through the terminal following these instructions here: 
http://docs.python-guide.org/en/latest/starting/install3/osx/

Please do make sure you've installed Python 3.6.

From there you can change the terminal directory to where ever you cloned the bot's repository to and follow the instructions steps from README.md.

-------------------------------------------------------------------------------------------------------------------
I'll be closing the ticket from here since OP doesn't seem to need help anymore.
