### ISSUE TITLE
Feature Request: Option to change command prefix

### ISSUE THREAD

**Issue by cryptochrome** [kodycode/CoinMarketDiscordBot#27]
Hi,

thanks for this awesome bot. I would like to request a feature: Let me change the command prefix from $ to anything else. Often different bots use the same command prefix, which leads to problems (both responding).

**Comment by kodycode** [comment]
Hey chrome,

That's a good point. I just added that feature as of https://github.com/kodycode/CoinMarketDiscordBot/pull/28. Feel free to pull the repo and edit the `cmd_prefix` value in config_template.json (or add the `cmd_prefix` key with the command prefix desired  into your existing config.json), and it should be good to go.

**Comment by cryptochrome** [comment]
Thank you, that was quick :)  Any chance to get to see this in the hosted version of the bot?

**Comment by kodycode** [comment]
Oh were you thinking of a bot command to change the prefix for your server?

**Comment by cryptochrome** [comment]
yes :)

**Comment by kodycode** [comment]
I think that's a cool feature to add. I'll come back with an update if I can get this idea going.

**Comment by kodycode** [comment]
Update,

I've managed to get down to adding the feature in as of https://github.com/kodycode/CoinMarketDiscordBot/pull/33. Also mentioned on the bot's command page and in the `$help` command, to change the prefix, all you have to do is `$prefix [whatever you want here]`. So if you did `$prefix !`, from there on the bot will only recognize `!` instead of `$`. 

If you ever forget the prefix, just `@` the bot and it will remind you of the prefix. 

If you see any problems, don't hesitate to reach out!
