### ISSUE TITLE
Bot went haywire, left our Discord

### ISSUE THREAD

**Issue by cryptochrome** [kodycode/CoinMarketDiscordBot#50]
Hey, 

yesterday something weird happened. The bot started posting on it's own without being queried by users, and all it would post would be messages like this:

> Invalid currency: otcha

It did that a few dozen times with different, unknown coin names. Then all of a sudden the bot leaves our server (and the bot role getting deleted).

**Comment by kodycode** [comment]
Yeah that was a huge mistake on my part..

I forgot to add a check for the command prefix when reading in messages as I was adding the new search shortcut. Just when I updated the bot and thought everything was peachy and fine, an hour later I check up on the bot and notice it’s been sending out spam and assumed every message was a command.

As the bot leaving on its own, I don’t actually know much about that but it may have done so because discord might have some kind of anti-spam prevention set up in cases where things go haywire.

It should be fixed now, however, do you notice anything else that’s weird?

**Comment by cryptochrome** [comment]
Nope, all good. And the bot leaving turned out to be a moderator on our server who panicked and kicked the bot :)   Case closed. Thank you!

**Comment by kodycode** [comment]
Alright good to know. Fingers crossed, hopefully there won't be another mess in the future.
