### ISSUE TITLE
Send updates to an channel

### ISSUE THREAD

**Issue by kkoepke** [kodycode/CoinMarketDiscordBot#55]
Can the bot also send his updates to a channel readable by everyone without the need to subscribe?

**Comment by kodycode** [comment]
Hey kkoepke,

I’m not quite sure I’m understanding this. The bot will post to a channel via the subscriber feature, and what determines if everyone else could see the bot’s updates is the permissions they have setup for their discord role. The bot relies on the subscriber feature in order to know what updates to send.

If users aren’t seeing updates made from the bot, you might need to enable the permission to read messages from the channel the bot is updating to.
